# Generated by Django 4.2.16 on 2024-09-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_long',
            field=models.FloatField(default=35.78, max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_lat',
            field=models.FloatField(default=35.78, max_length=100),
        ),
    ]
